name: "Terraform CI/CD with OpenTofu - Deployment"

on:
  workflow_run:
    workflows: ["Terraform CI/CD with OpenTofu - Planning"]  # Trigger this after the planning workflow is complete
    types:
      - completed

permissions:
  id-token: write

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: "Approval for Deployment"
        run: |
          echo "Deployment is pending approval."
          # This step can be a manual review trigger, and you can insert instructions for approval if needed.
  
  terraform:
    needs: approval  # Ensure deploy only happens after approval
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Azure
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "Setting up Azure authentication"
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OpenTofu
        run: |
          TOFU_VERSION="1.6.2"
          curl -LO "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.zip"
          unzip -o tofu_${TOFU_VERSION}_linux_amd64.zip
          sudo mv tofu /usr/local/bin/tofu

      - name: Format Terraform code
        run: tofu fmt -recursive
        working-directory: terraform

      - name: Initialize Terraform with backend config
        run: tofu init -backend-config=backend.yaml
        working-directory: terraform

      - name: Validate Terraform configuration
        run: tofu validate
        working-directory: terraform

      - name: Plan Terraform changes
        run: tofu plan -out=tfplan
        working-directory: terraform

      - name: Upload Terraform plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

      - name: Apply Terraform changes
        run: |
          tofu apply tfplan
        working-directory: terraform
