name: "Terraform CI/CD with OpenTofu"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          TOFU_VERSION="1.6.2" # or latest known good version
          curl -L "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.tar.gz" -o tofu.tar.gz
          tar -xzf tofu.tar.gz
          sudo mv tofu /usr/local/bin/tofu
      

      - name: Format Terraform Code
        run: tofu fmt -recursive

      - name: Initialize Terraform
        run: tofu init -backend-config=terraform/backend.yaml

      - name: Validate Terraform Configuration
        run: tofu validate

      - name: Plan Terraform Changes
        run: tofu plan -out=tfplan
